const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]||'screen-checks');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const rel=decodeURIComponent(req.url.split('?')[0]);if(rel==='/qa.html'){res.setHeader('Content-Type','text/html');return res.end(`<meta name="viewport" content="width=device-width,initial-scale=1"><script src="wam-campaign.js"></script><script src="wam-engine.js"></script><script src="wam-ui.js"></script>`);}const file=path.resolve(root,'.'+rel);if(!file.startsWith(root+'/')||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.jpg')?'image/jpeg':'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:414,height:896},hasTouch:true,reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(`http://127.0.0.1:${server.address().port}/qa.html`);
assert.equal(await page.evaluate(()=>WamCampaign.TOTAL),100);
assert.ok(await page.evaluate(()=>WamCampaign.levels.every(l=>l.background==='artwork/lounge-levels.jpg')));
for(const size of [{width:414,height:896},{width:900,height:1440}]){await page.setViewportSize(size);for(const id of [1,5,9,21,30,40,70,100]){await page.evaluate(id=>{window.v?.dispose();localStorage.setItem('wambam-unlocked-level','100');localStorage.setItem('wambam-selected-level',id);for(const b of WamCampaign.BOOSTERS)localStorage.setItem('wambam-stock-'+b,3);window.v=new WamUI.GameView({});},id);await page.getByRole('button',{name:'LET’S PLAY',exact:true}).click();await page.locator('.wam-art').evaluate(img=>img.decode());
const checks=await page.evaluate(()=>{const s=v.stage.getBoundingClientRect(),r=v.board.getBoundingClientRect(),k=s.width/720;return {loaded:v.stage.querySelector('.wam-art').naturalWidth>800,inFrame:r.left>=s.left+125*k&&r.right<=s.left+599*k&&r.top>=s.top+350*k&&r.bottom<=s.top+953*k,onScreen:s.left>=-1&&s.top>=-1&&s.right<=innerWidth+1&&s.bottom<=innerHeight+1};});assert.ok(Object.values(checks).every(Boolean),JSON.stringify(checks));
for(const name of ['Lip Laser','Heel Smash','Disco Ball','Free Swap']){await page.getByRole('button',{name,exact:true}).click();assert.equal(await page.getByRole('button',{name,exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name,exact:true}).click();}
await page.getByRole('button',{name:'Pause game',exact:true}).click();await page.getByRole('button',{name:'RESUME',exact:true}).click();
if(id===5||id===100)await page.screenshot({path:path.join(out,`level-${id}-${size.width}.png`)});
}}
await page.evaluate(()=>{v.dispose();localStorage.setItem('wambam-selected-level','1');window.v=new WamUI.GameView({});});await page.getByRole('button',{name:'LET’S PLAY',exact:true}).click();const before=await page.evaluate(()=>v.game.moves),move=await page.evaluate(()=>v.game.hint());assert.ok(move);await page.locator(`[data-cell="${move[0]}"]`).click();await page.locator(`[data-cell="${move[1]}"]`).click();await page.waitForFunction(()=>!v.busy);assert.equal(await page.evaluate(()=>v.game.moves),before-1);assert.equal(await page.locator('.wam-moves').textContent(),String(before-1));assert.deepEqual(errors,[]);console.log('PASS: 100 level backgrounds; phone/tablet board bounds; four booster controls; pause/resume; playable swap and live moves.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
